### ISSUE TITLE
Empty filter and sorting array causes issues

### ISSUE THREAD

**Issue by isaacmattern** [ndimatteo/HULL#105]
When filters and sorts are disabled, the collection-grid module still looks for items in each of these arrays and raises an issue which prevents rendering. This took awhile for me to figure out, and in order to resolve this issue, you have to add an item to the sort or filter array in shop settings.

<img width="476" alt="Screen Shot 2022-08-24 at 5 48 26 PM" src="https://user-images.githubusercontent.com/77303978/186529606-627ab777-57b0-4575-aeea-78a40fbb5b6f.png">

Above is an example of an error shown when trying to render a collection before you've added a sort to the sort array in shop settings.

**Comment by ndimatteo** [comment]
Hey there @isaacmattern sorry about that!

This is a good catch, glad you were able to resolve it. I just added a few more checks so that it doesn't fail if that data's not set in the Shop Settings.

**Comment by isaacmattern** [comment]
awesome! thank you so much for the quick fix
