### ISSUE TITLE
Shopify Product Images not syncing to Sanity

### ISSUE THREAD

**Issue by GodwinEbikwo** [ndimatteo/HULL#109]
Hi, thank you @ndimatteo  for this project, everything seems to work fine including the setup.
However, when I update my products in Shopify, the images, and product description doesn't sync into the sanity studio. 
Only Price, and Product name syncs well.

Please is this the expected behavior ?

Thank you for your response !
<img width="1440" alt="Screen Shot 2022-11-20 at 06 35 08" src="https://user-images.githubusercontent.com/43885112/202889328-d0a3d930-55ab-418a-82eb-8bfa3320afc8.png">

**Comment by kuleyu** [comment]
Yes, that is the expected behavior recently. You need to add these contents in this panel by yourself.

**Comment by ndimatteo** [comment]
Hey there @GodwinEbikwo as @kuleyu mentioned, this is the intended functionality. We only sync the bare minimum needed for products to power the add-to-cart and checkout experience. You can see what those are here: https://github.com/ndimatteo/HULL/blob/main/pages/api/shopify/product-update.js#L101-L116

Anything for **presentation** purposes is not sync'd between Shopify and Sanity. Instead, it lives in Sanity alone, allowing you to extend functionality and build custom product pages.

I hope that helps explain things!
