### ISSUE TITLE
Missing api sync functions?

### ISSUE THREAD

**Issue by rudin** [ndimatteo/HULL#11]
Hi Nick,

Great project!
I was fiddling around and found that the product sync functions are not (yet) in place?

**Comment by ndimatteo** [comment]
@rudin thanks!

What do you mean? The product sync API endpoints are all setup here: https://github.com/ndimatteo/HULL/tree/main/pages/api/shopify

You will need to follow steps [2](https://github.com/ndimatteo/HULL#2-shopify-storefront-access) and [3](https://github.com/ndimatteo/HULL#3-shopify-webhooks), as well as adding your `.env` variables, in order for these to work properly with your implementation 🤘
