### ISSUE TITLE
floating-ui.dom.esm.js sanity build issue

### ISSUE THREAD

**Issue by deviomedia** [ndimatteo/HULL#114]
Problem with building the studio. This happens without any previous changes so I guess its related to a package thats been used.

Error in ./node_modules/@floating-ui/dom/dist/floating-ui.dom.esm.js
Module parse failed: Unexpected token (307:11)
You may need an appropriate loader to handle this file type.
|   }
| 
|   return { ...rect,
|     x: rect.x - scroll.scrollLeft + offsets.x,
|     y: rect.y - scroll.scrollTop + offsets.y

**Comment by kasperbirch1** [comment]
It sounds like the same issue here. 
https://github.com/ndimatteo/HULL/issues/110

**Comment by alfredoLipari** [comment]
Same here, I am unable to deploy on vercel a brand new one template

**Comment by ndimatteo** [comment]
@Rosewives you're mentioning the wrong plugin, it's the `sanity-plugin-media` that you will need to update, **not** the note-field plugin.

@alfredoLipari @deviomedia please try updating with:
```
yarn add sanity-plugin-media@1.4.13
```

**Comment by Rosewives** [comment]
> @Rosewives you're mentioning the wrong plugin, it's the `sanity-plugin-media` that you will need to update, **not** the note-field plugin.
> 
> @alfredoLipari @deviomedia please try updating with:
> 
> ```
> yarn add sanity-plugin-media@1.4.13
> ```

Thanks @ndimatteo for the correction, I just realized I referred to a wrong plugin.

@alfredoLipari @deviomedia Just rewrite the line 30 of this file "[HULL/studio/package.json](https://github.com/ndimatteo/HULL/blob/1242524b99d3b1495075011a26012a25bcc9b374/studio/package.json#L30)", change it from `    "sanity-plugin-media": "^1.4.0",` to `    "sanity-plugin-media": "1.4.3",` , then the issue would be solved.

**Comment by ndimatteo** [comment]
I just pushed up some changes which included updating packages for the `studio` ✨ 

I was able to install and run it without any build errors so I'm going to close this, but if anything comes up please open a new issue. Thanks, everyone! 🤘
