### ISSUE TITLE
Project decisions

### ISSUE THREAD

**Issue by frempongandrews** [ndimatteo/HULL#115]
Hi I have had a look at the project and it is really great. Congrats for the amazing job!

My question is: Why would I or a client want to sync my content/products between shopify and sanity?

Hope to hear from you soon

**Comment by ndimatteo** [comment]
Hey there @frempongandrews thanks for the kind words!

It may be worth taking a step back from this project specifically and diving into the pros/cons of what a "headless" Shopify experience offers. That is at the core of why we are sync'ing data between Shopify and Sanity, and I think if you have an understanding of that, the answer to your original question will become clear.

You can start by reading a few articles, [here's one](https://www.shopify.com/enterprise/headless-commerce) that will point you in the right direction.

I hope that helps! Good luck!

**Comment by frempongandrews** [comment]
thanks you! ✌️
