### ISSUE TITLE
Product data changes not geting properly synced to Sanity if there's another product with same slug

### ISSUE THREAD

**Issue by ansmlc** [ndimatteo/HULL#116]
In scenario where there's two products with an identical **slug** field present in Sanity Studio, changing product data in Shopify doesn't update (any of) the auto-synced product data in Sanity. This seems strange because the update API takes into consideration product's id, which is of course different.  At the same time, the functions log in Vercel shows successfully sync message every time. 

If there's a new brand new product added (that doesn't have a duplicate) sync works as expected, which suggests the issue is specifically related to there being a duplicate slug field:

![vercel_function_logs](https://user-images.githubusercontent.com/50321640/208743788-dce5c2ea-bb87-4b2c-90e8-464900fe0f6a.jpg)

The yellow-marked part is a console-log is from `product-update.js`, checking the "URL Handle" Shopify field :

```

api/shopify/product-update.js (line 78)

console.log(handle, '**** Current handle ****')

```
The `handle` that's printed is in fact the correct, newly edited URL Handle from Shopify. However, it **doesn't get reflected in Sanity:**
<img width="314" alt="image" src="https://user-images.githubusercontent.com/50321640/208754246-11079d19-ab4c-460f-b66c-8ff17d910184.png">

I than tried making some changes the API to force a change for the slug field, in :

```
// api/shopify/product-update.js


 const slugField = {
    slug: {
      current: handle,
    }
  }

  // patch (update) slug, missing or not 
  stx = stx.patch(`product-${id}`, (patch) => patch.set(slugField))
  
// Add to productCompare set:
  const productCompare = {
    ...product,
    ...productFields,
    ...slugField,
    ......
  }


```

That didn't work so I tried to **unset** the field:

```

 // unset slug field

 const slugField = ["slug"];
 stx = stx.patch(`product-${id}`, (patch) => patch.unset(slugField))

```

which didn't work either.

As to why there are products with duplicate slug values, it's a result of switching to different Shopify store which had cloned all product data from previous store, so now there's duplicate products with duplicate slugs, neither of which can be deleted, and the new products can't be published either because of the duplicate slug validation error.

**Comment by ansmlc** [comment]
I've managed to "remove" the duplicate product by adding this to _product-delete.js_ API:
`  stx = stx.patch(`product-${idNew}`, (patch) => patch.set({ wasDeleted: true }))`

The product is now _marked_ as "removed" in Sanity but the document is still there, and still giving the same "slug in use" warning:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/50321640/209271070-063ca1f7-ee54-462e-a78e-cda63684b6dd.png">

Because of this slug conflict error the client still can't publish the proper product.

**Comment by ndimatteo** [comment]
Hey there @ansmlc by default [Sanity checks for uniqueness](https://www.sanity.io/docs/slug-type#validation) on `slug` fields for documents.

This is why it's not updating anything in Sanity when the sync function occurs. You can actually see the error message after the sync starts in your first screenshot:

<img width="986" alt="Screenshot 2022-12-28 at 4 18 02 PM" src="https://user-images.githubusercontent.com/737188/209884228-29753989-4ae2-4aef-b8cf-b908eb401fe1.png">


You'll need to either delete the previous documents **_(and remove all references to those elsewhere first)_**, or you can try overriding the default validation for the product slug fields in your schema to allow it to create product documents with the same slug values.

Let me know if that helps! 🤘

**Comment by raqibnur** [comment]
is there any way to check the localhost sanity error log? mine is not syncing

**Comment by ndimatteo** [comment]
@Raqibnur please open a separate issue with more details about what you are experiencing, instead of commenting on other people's issues that are still open 🤘

**Comment by ansmlc** [comment]
@ndimatteo This has been resolved by rolling back to an older dataset backup and avoiding having same-slug documents.
