### ISSUE TITLE
Order Status Domain

### ISSUE THREAD

**Issue by kkcy** [ndimatteo/HULL#117]
Referring to your example, the orders status page's domain would be something like `https://shop.hull.dev/12345/orders/12345` yeah?

I'm pretty sure it isn't possible, but just wanted to confirm if it is possible to have it under `https://hull.dev/12345/orders/12345`?

**Comment by ndimatteo** [comment]
Hey there @kkcy you are correct! The default order status pages generated by Shopify would be part of the domain attached to your native Shopify account, _not_ your headless domain.
