### ISSUE TITLE
Analytics Support

### ISSUE THREAD

**Issue by sebszocinski** [ndimatteo/HULL#12]
I'm guessing because you're using the GraphQL Buy SDK which doesn't support Shopify's built in Analytics there is no support for any analytics or metric tracking such as view product, add to cart or start a checkout?

**Comment by ndimatteo** [comment]
@sebszocinski yes, since we are outside of Shopify Native you will need to roll your own analytics for tracking things like that!

I have some helper functions to get you started with that though, which you can find here: https://github.com/ndimatteo/HULL/blob/main/lib/gtm.js

I hope that helps! 🤘
