### ISSUE TITLE
Is it true that you have to redeploy every time a product is added?

### ISSUE THREAD

**Issue by robksawyer** [ndimatteo/HULL#120]
I've recently set this up because it looks rad! Nice work on everything. I'm trying to get used to the workflow and wanted to confirm that I do in fact need to deploy via Sanity (and have the app rebuild on Vercel) before new products appear. It's not enough to just add them to Sanity Studio? 

My current process (which isn't great and is time consuming):
- Add product in Shopify
- This data shows up in Sanity (images/description content do not)
- Complete the listing by adding images and description content 
- Publish and then using the Deploy tab, deploy the app
- Wait 4 minutes while Vercel rebuilds the app

**Comment by robksawyer** [comment]
It's been months since I've had to add a product and now when I go to deploy, I am getting the following error on Vercel. Can someone remind me where I should start debugging this?

`TypeError: Cannot destructure property 'options' of 'activeVariant' as it is undefined.`

**Comment by benitodotcool** [comment]
Hey @robksawyer,
As explain inside the README.md:

> ### Client Updates
> Once you hand off to the client you'll want to give them the ability to generate builds when they make updates within the Sanity Studio. The easiest way to do this is through my [Vercel Deploy plugin](https://github.com/ndimatteo/sanity-plugin-vercel-deploy).

I'm not currently using this template, but it seems that @ndimatteo also developed a Sanity [plugin](https://github.com/ndimatteo/sanity-plugin-vercel-deploy) that allows this.

### **Here is what I understand:**

1. The website uses Static Generation to be fast.
2. The website uses something to get live product's quantity, so static pages shows the ‘Add to cart’ or ‘Sold out’ button.
3. So if you don't trigger the deploy on Vercel, it's normal that you don't have any difference.

I can missunderstand something here, but I think it's the way this template works.

I hope it helps you.

All the  best,

Benito

**Comment by Dujota** [comment]
you will need to trigger a bulld through the vercel serverless functions in order to revalidate the static pages, alternatively you can use the isg feature of next js to rebuild pages after some time. (basically cache page build for a certain amount of time and the bust cache, force a particular page to re-generate) 

on many sanity projects I have done for clients the revalidate option has worked great, content editor makes a change and publishes, then the page will udpate when the validate timer expires for a given client, once they leave the page and come back or reload the page,

**Comment by ndimatteo** [comment]
hey there @robksawyer – I'm just doing some issue maintenance here. Going to close this one, but to reiterate what @Dujota mentioned already:

1. Yes, by default, you will need to rebuild your site when _new_ products are added in Shopify, or any changes are made in _Sanity_. This is the standard flow for Static Site Generation (SSG).
2. You can automate this by using [ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration), or page-level revalidation if you wish
