### ISSUE TITLE
Mobile Crashes When Interacting On Page

### ISSUE THREAD

**Issue by obiknows** [ndimatteo/HULL#126]
First of all, 

Really love this theme. Putting it to use currently for a clothing brand. 

The site functions fine on desktop, however on mobile, when interacting with the page I'll occasionally get client-side errors and crashes. I thought it was just me, but this happens on https://hull.dev when I interact from a mobile browser as well.

Does any one else have this issue? If so, what's the remedy?

Thanks in advance,

Obinna

**Comment by ndimatteo** [comment]
Hey there @obiknows,

Glad you're digging it!

Would you be able to provide any more info on the errors you're encountering? It would be helpful to know what browser and device (along with versions) you are experiencing this on.

And if there are any reproducible steps to replicate what you're seeing. Thanks! 🤘

**Comment by obiknows** [comment]
Yeah totally @ndimatteo. Thanks for building this and replying back, btw.


Just tested Safari and all seems well, but in Brave (Chromium based browser) on an iPhone 11 it seems to error out on links.

Tested on https://hull.dev and this is the issue I have on my personal website as well.



https://github.com/ndimatteo/HULL/assets/10480589/4e1727da-d2a8-4d83-97d4-8870da1db849



This doesn't seem to be an issue when using the mobile viewport in a Desktop browser, so I'm unable to get error logs from the browser unfortunately. A mobile only issue.

I don't see any error in Vercel logs either.


This is my User Agent:

`Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1`

**Comment by obiknows** [comment]
Found a fix on my end,

Had to purge the cache in Vercel and the issue magically resolved.

Hope this helps somebody.

**Comment by ndimatteo** [comment]
Interesting @obiknows! I appreciate the details you shared, very interesting edge case here it seems.

Just out of curiosity, is the [hull.dev](https://hull.dev) demo still causing errors for you? I assume so, given the fix you mentioned, but I just want to be sure it's project-specific on Vercel, and related to the cache.

**Comment by obiknows** [comment]
Yes, the [hull.dev](https://hull.dev) site still errors out in my mobile browser as of right now

> Interesting @obiknows! I appreciate the details you shared, very interesting edge case here it seems.
> 
> 
> 
> Just out of curiosity, is the [hull.dev](https://hull.dev) demo still causing errors for you? I assume so, given the fix you mentioned, but I just want to be sure it's project-specific on Vercel, and related to the cache.

**Comment by ndimatteo** [comment]
Thanks for confirming 🤘 I just purged the cache. Hopefully, it's working properly now for you!
