### ISSUE TITLE
marketing starter upgrade packages

### ISSUE THREAD

**Issue by pcavendano** [ndimatteo/HULL#127]
Hey everybody,

I've tried to use the marketing starter project and after npm install i have a lot of packages that are too old.

What will be the best aproach here, i love this project and i'll like to use it as a starter for my non ecomerce projects.

I saw that the project on the main branch was being updated, should i juste use the main branch and try to remove the shopify stuff?

Thanks in advance for your help 

![image](https://github.com/ndimatteo/HULL/assets/45802239/f14510b2-263c-48e2-b6cb-aeb082936d6e)

**Comment by ndimatteo** [comment]
Hey there @pcavendano – Apologies, the `marketing` starter is a bit outdated at this point. I'd definitely recommend using the `main` branch and just removing all of the ecommerce bits that are not needed!
