### ISSUE TITLE
Issue cloning project from Vercel

### ISSUE THREAD

**Issue by AP-monkey** [ndimatteo/HULL#135]
Hello, I am having many issues deploying the project to Vercel (https://vercel.com/templates/next.js/hull-sanity-shopify).
I tried the automatic path and the manual path, and at both I was stuck. Did anyone else experience any issues deploying the project do vercel and following the instructions?

Following the manual installation, I get the project successfully deployed but I get stuck at this error: "Home Page" is not set in Sanity, or the page data is missing.

while following the automatic installation (to see the demo store) I cannot even deploy it. I added all the Environment Variables and tried to redeploy, but I keep on getting this error: 

`
TypeError: Cannot read properties of undefined (reading 'replace')
--
19:00:54.093 | at /vercel/path0/.next/server/chunks/322.js:1366:31
19:00:54.093 | at Array.map (<anonymous>)
19:00:54.093 | at replaceTemplateTags (/vercel/path0/.next/server/chunks/322.js:1365:18)
19:00:54.093 | at HeadSEO (/vercel/path0/.next/server/chunks/322.js:1245:23)
19:00:54.093 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
19:00:54.093 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
19:00:54.093 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
19:00:54.094 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
19:00:54.094 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
19:00:54.094 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
19:00:54.094 |  
19:00:54.094 | Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
19:00:54.094 | TypeError: Cannot read properties of undefined (reading 'replace')
19:00:54.094 | at /vercel/path0/.next/server/chunks/322.js:1366:31
19:00:54.094 | at Array.map (<anonymous>)
19:00:54.095 | at replaceTemplateTags (/vercel/path0/.next/server/chunks/322.js:1365:18)
19:00:54.095 | at HeadSEO (/vercel/path0/.next/server/chunks/322.js:1245:23)
19:00:54.095 | at Wc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
19:00:54.095 | at Zc (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
19:00:54.095 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
19:00:54.095 | at $c (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
19:00:54.095 | at bd (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
19:00:54.095 | at Z (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

`

**Comment by ndimatteo** [comment]
Hey there @AP-monkey,

Please reference these comments from other issues:
1.https://github.com/ndimatteo/HULL/issues/136#issuecomment-1961637363
2. https://github.com/ndimatteo/HULL/issues/119#issuecomment-1452322590

You need to make sure you have all `.env` variables set in Vercel, and that global site and page data is set in Sanity.
