### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by hanii090** [ndimatteo/HULL#136]
![Screenshot 2024-02-09 145908](https://github.com/ndimatteo/HULL/assets/131614433/8960d12f-81ff-4893-b527-8899053d889d)
How do i resolve this!

**Comment by skylerstyron** [comment]
What were you doing to get this issue?

If you are creating a new page, you need to add all seo fields.

**Comment by ndimatteo** [comment]
Hey there @hanii090,

As @skylerstyron pointed out, make sure you have all proper data (including settings) filled out in Sanity. This bug only appears when there is core data objects missing when generating pages.

As mentioned in other issues– in the next version of HULL these issues will be addressed.
