### ISSUE TITLE
I got the same error after following the directions.  I cloned the repository with git clonee and followed the instructions in the ReadMe.md file in the root.  Localhost:3333 and localhost:3000 are running, I don't see any errors.

### ISSUE THREAD

**Issue by enterpriseSoftware** [ndimatteo/HULL#137]
I got the same error after following the directions.  I cloned the repository with git clonee and followed the instructions in the ReadMe.md file in the root.  Localhost:3333 and localhost:3000 are running, I don't see any errors.
$ yarn dev
yarn run v1.22.21
warning ..\package.json: License should be a valid SPDX license expression
$ cross-env NODE_ENV=development next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\SourceControl\HULL\.env.local
event - compiled client and server successfully in 8.7s (1836 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2s (1937 modules)

$ yarn dev
yarn run v1.22.21
warning ..\..\package.json: License should be a valid SPDX license expression
$ sanity start

   ╭────────────────────────────────────────────╮
   │                                            │
   │     Update available 2.36.2 → 3.30.0       │
   │   Run yarn upgrade @sanity/cli to update   │
   │                                            │
   ╰────────────────────────────────────────────╯

[WARN] The following package versions have not yet been marked as supported:

  react (installed: 18.2.0, want: ^16.9 || ^17)
  react-dom (installed: 18.2.0, want: ^16.9 || ^17)

You _may_ encounter bugs while using these versions.

  To downgrade, run either:

  yarn add "react@17.0.0" "react-dom@17.0.0"

  or

  npm install "react@17.0.0" "react-dom@17.0.0"

✔ Checking configuration files...
⠙ Compiling...webpack built cb72540ebe37085a9011 in 16584ms
✔ Compiling...
Content Studio successfully compiled! Go to http://localhost:3333
![localhost3333](https://github.com/ndimatteo/HULL/assets/6784635/0f1e2460-9189-4be9-8639-378e5a3b6c1f)

_Originally posted by @enterpriseSoftware in https://github.com/ndimatteo/HULL/issues/99#issuecomment-1960788370_

**Comment by enterpriseSoftware** [comment]
I went through all the steps. Does this have to be deployed to Vercel first to obtain an url before it works?  I didn't fill out any webhooks yet.   Also I didn't know the hostname because I didn't have one.   I had only one question following 
![publicaccesstoken](https://github.com/ndimatteo/HULL/assets/6784635/70ca46eb-a0f8-4f60-ac9c-109b7dd53a8b)
the instructions.  The SHOPIFY_ADMIN_API_TOKEN I was unsure about. I used this public token.  Was that the right choice?

![publicaccesstoken](https://github.com/ndimatteo/HULL/assets/6784635/927b0517-b760-4016-b9e6-213d2813640a)

Also since I have not deployed, I put an arbitrary value here.
![hostname](https://github.com/ndimatteo/HULL/assets/6784635/0d381458-753a-4fd5-95bc-639ba8cd0609)
thank yoiu in advance.
tim

**Comment by ndimatteo** [comment]
Hey there @enterpriseSoftware please don't duplicate content across comments/issues, and try to keep issue titles short and specific to a single problem.

1. You do not need to be deployed to Vercel for the website to run locally.
2. I'm not sure what you're setting up that `hostname` value for. The only edits you should be making to your native shopify theme is outlined [here](https://github.com/ndimatteo/HULL?tab=readme-ov-file#5-shopify-store-theme).

I hope that helps, closing this issue as this issue is not formatted correctly and largely revolves around not completing the install instructions.
