### ISSUE TITLE
Sanity Create Project is not working

### ISSUE THREAD

**Issue by AbhieShinde** [ndimatteo/HULL#139]
https://www.sanity.io/create?template=ndimatteo/HULL this URL redirects me to template page?

**Comment by ndimatteo** [comment]
@AbhieShinde Sanity revamped their template setup and removed the `create` flow. I referenced this in a previous issue here: https://github.com/ndimatteo/HULL/issues/132#issuecomment-1863301929.

Please follow the manual setup steps to get going 🤘

**Comment by AbhieShinde** [comment]
I got it, but what steps should I follow to get the marketing starter app fully running?

**Comment by AbhieShinde** [comment]
I'm sure about the sanity studio, even after following the introductions I'm not able to get the data.
