### ISSUE TITLE
inputComponent: ConditionalFields breaks hotspot

### ISSUE THREAD

**Issue by dnlmzw** [ndimatteo/HULL#14]
Hi there,
Although this isn't the core to what you made, I still thought I'd want to mention that `hotspot` on image assets stops working, when using your ConditionalFields script.

**Comment by ndimatteo** [comment]
Hey there @dnlmzw !

Can you let me know what you mean?

Are the hotspot options not showing up for `figure` fields used in conditional fields? Or are you not seeing hotspots being applied on the front-end? Or something else?

Just a few preliminary comments:
1. If you are adding new image fields you'll need to use the [`imageMeta` GROQ from the api](https://github.com/ndimatteo/HULL/blob/main/lib/api.js#L17-L27) to ensure the hotspot data makes it into the frontend. 
2. If you have that in place are you able to log the photo data somewhere to see if your hotspot data is coming through?
3. If the hotspot options aren't showing up in your Studio, this tells me it's an issue with the custom Conditional Field plugin, which was adapted from here: https://gist.github.com/coxmi/f41aef54d46588fff27651cd0d35212f

**Comment by dnlmzw** [comment]
Thanks! Option 3 is what's happening, so I'll head over there and see if there's anything to be done.

**Comment by dnlmzw** [comment]
For anyone else interested:

I took the one from @hdoro that [can be found here](https://github.com/hdoro/sanity-plugin-conditional-field/blob/881d8ffdd776bcc6aaa071cd416d968027a53a40/src/ConditionalField.tsx#L32-L54) and included the `getContext` bit from you script and the hotspot is now working.

```
import React from 'react'
import {
  withDocument,
  withValuePath,
  FormBuilderInput
} from 'part:@sanity/form-builder'

class ConditionalField extends React.PureComponent {
  fieldRef = React.createRef()

  focus() {
    if (this.fieldRef?.current) {
      this.fieldRef.current.focus()
    }
  }

  getContext(level = 1) {
    // gets value path from withValuePath HOC, and applies path to document
    // we remove the last 𝑥 elements from the valuePath

    const valuePath = this.props.getValuePath()
    const removeItems = -Math.abs(level)
    return valuePath.length + removeItems <= 0
      ? this.props.document
      : valuePath.slice(0, removeItems).reduce((context, current) => {
          // basic string path
          if (typeof current === 'string') {
            return context[current] || {}
          }

          // object path with key used on arrays
          if (
            typeof current === 'object' &&
            Array.isArray(context) &&
            current._key
          ) {
            return (
              context.filter(
                item => item._key && item._key === current._key
              )[0] || {}
            )
          }
        }, this.props.document)
  }

  render() {
    const {
      document,
      type,
      value,
      level,
      focusPath,
      onFocus,
      onBlur,
      onChange,
      getValuePath,
      markers = [],
      presence = [],
      compareValue
    } = this.props
    const shouldRenderField = type?.options?.condition
    const renderField = shouldRenderField
      ? shouldRenderField(document, this.getContext.bind(this))
      : true

    if (!renderField) {
      return <div style={{ marginBottom: '-32px' }} />
    }

    const { type: _unusedType, inputComponent, ...usableType } = type
    return (
      <FormBuilderInput
        level={level}
        type={usableType}
        value={value}
        onChange={patchEvent => onChange(patchEvent)}
        path={getValuePath()}
        focusPath={focusPath}
        onFocus={onFocus}
        onBlur={onBlur}
        ref={this.fieldRef}
        markers={markers}
        presence={presence}
        compareValue={compareValue}
      />
    )
  }
}

export default withValuePath(withDocument(ConditionalField))
```
