### ISSUE TITLE
@reach/rect error

### ISSUE THREAD

**Issue by FawnHux** [ndimatteo/HULL#140]
Hello! 

Within the past week, when redeploying our HULL-adapted project with Vercel we encountered this error: 
Could not resolve dependency: npm ERR! peer react@"^16.8.0 \|\| 17.x" from @reach/rect@0.18.0. I checked your base files and they are the same react@18.2.0 / @reach/rect@0.18.0. It's odd as previously worked fine. For now we have just applied the overide in the package,  but good to know if anyone else is experiencing this or has used a different package.

**Comment by ndimatteo** [comment]
Seems like something has degraded with this package, and unfortunately, it's [no longer maintained](https://github.com/reach/reach-ui/issues/972).

I've switched to using @wellyshen's package for measuring refs: https://github.com/wellyshen/react-cool-dimensions

It's a quality package that is suited to replace most instances of `@reach/rect` 🤘 

Hopefully that helps! And as a friendly reminder– I'm working on a new version of HULL (largely a rewrite), and as a result not actively updating the current version unfortunately. Stay tuned!

**Comment by manoxs** [comment]
Overwritting the npm install to yarn install did the build for me 
![image](https://github.com/user-attachments/assets/b382668c-bbd0-472f-bae0-ffd73e20745b)
