### ISSUE TITLE
Build error after syncing shopify products 

### ISSUE THREAD

**Issue by highsandlows** [ndimatteo/HULL#15]
After uploading syncing some new products from shopify store a build error occurs.

Shopify store is in development mode.    

<img width="964" alt="Screen Shot 2021-05-27 at 11 16 40 pm" src="https://user-images.githubusercontent.com/84060259/119911900-e5672180-bf8c-11eb-9328-fa147120c1e3.png">
<img width="1015" alt="Screen Shot 2021-05-27 at 11 18 13 pm" src="https://user-images.githubusercontent.com/84060259/119911914-e9933f00-bf8c-11eb-906b-346452b34e9c.png">

**Comment by ndimatteo** [comment]
Hey there @highsandlows !

It sounds like you have a "collections" module on the homepage that has no products listed or is citing a now removed product. Can you confirm this error is for the homepage and what modules you have setup there?

Any more info you have would be helpful!

**Comment by ndimatteo** [comment]
Closing for now, as I haven't heard back! Hope the above resolved it for you 🤘
