### ISSUE TITLE
Add to Cart from Collection page

### ISSUE THREAD

**Issue by LeoSonnekus** [ndimatteo/HULL#16]
Hey I love this starter and have built a decent portion of a new client site with it,

I need to add the Add to Cart to  the collection page for each product tile, is there an easy way to do that?

Any support would be really appreciated.

**Comment by ndimatteo** [comment]
Hey there @LeoSonnekus glad you're enjoying it!

As for including an "Add to Cart" button at the collection level, it's actually pretty easy to do!

You can use the existing `product-add` block from here: https://github.com/ndimatteo/HULL/blob/main/blocks/product/product-add.js

Simply include this on your collection product cards, and feed it the `activeVariant.id`:

```js
<ProductAdd productID={activeVariant.id}>Quick Add</ProductAdd>
```

Let me know if that makes sense and/or if you have further questions!

**Comment by LeoSonnekus** [comment]
Legend thanks @ndimatteo

**Comment by ndimatteo** [comment]
For sure @LeoSonnekus!
