### ISSUE TITLE
Promo-bar breaks site when link isn't set

### ISSUE THREAD

**Issue by dnlmzw** [ndimatteo/HULL#21]
https://github.com/ndimatteo/HULL/blob/d207a173970b0eba68ee067221cf45886c2f3e8d/modules/shared/promo-bar.js#L25

Should be `text` instead of `{ text }`

**Comment by ndimatteo** [comment]
Good catch @dnlmzw ! Will have this updated in the next release :)

**Comment by ndimatteo** [comment]
Fixed in latest updates!
