### ISSUE TITLE
Accounts and Logins

### ISSUE THREAD

**Issue by LeoSonnekus** [ndimatteo/HULL#22]
Hey I noticed the Account links to this url - https://go.insane.codes/account/login how do I connect my Shopify login/account flow and can I access User information on the Client if they've logged in through Shopify? would be really interested to know how Shopify - Auth  is handled :)

**Comment by ndimatteo** [comment]
Hey there @LeoSonnekus !

I'm not sure where you're seeing that URL being linked, but on the HULL demo it should be linking to here: https://shop.hull.dev/account/login

(password is `hull-demo` if you want to preview how it looks)

In any case, you will have to setup accounts yourself, as that's not currently something offered out of the box with HULL. In the demo, we're simply using the Shopify native theme to handle the account flow. We call this a "hybrid" approach, where your store is headless, but accounts are native.

In the near future I plan to have a headless solution for accounts as well, but for now I'd suggest going the "hybrid" route or rolling your own custom headless solution.

**Comment by LeoSonnekus** [comment]
Hey @ndimatteo 

I thought that might be the case, hybrid sounds like a good approach.

I mostly ask because I'm migrating a Shopify store to headless in a few months that relies quite heavily on the Account ordering flow and just needed to see what the limitations are.

For my current project I have a login flow as a payment wall to access video courses on a blog like page structure that I've added alongside the e-commerce functionality so what I'm planning on doing is using all the features that Hull so generously has setup already and building a firebase + stripe based auth for the other services. 

Should be interesting, do keep us posted on how you go with the headless Account flow that would be sick but in the meantime thanks again for this project  :)

**Comment by ndimatteo** [comment]
That's awesome @LeoSonnekus! I definitely think if you're wanting all the features that come with shopify user accounts, the hybrid approach will be great, as you'll get everything out of the box with them from that.

Rolling headless accounts for Shopify is a bit challenging from both a security standpoint and all the API requirements to manage all the different aspects (account info, shipping info, orders, etc).

Definitely will keepe everyone posted as we get closer to adding that into HULL! 🤘

**Comment by Brett-SustainedAffair** [comment]
> 
> In the demo, we're simply using the Shopify native theme to handle the account flow. 
> 

Hi Nick,

I visited the account flow on the demo site, it looks great and fits in with the HULL desgin. How did you customise the page layout? Is is defined in the 'theme.liquid' file?

**Comment by ndimatteo** [comment]
Hey there @Brett-SustainedAffair!

The native "accounts" pages are part of the theme files that I modified a bit to better match the headless design.

The `theme.liquid` file is not where this is defined, as that file only handles which pages redirect to the headless side of things. You'll need to edit the associated theme template liquid files.

To match the styles, I simply copied over the compiled CSS from the headless side into the `theme.css` file in the Shopify theme assets file and then adjusted the HTML in the template files.

I hope that helps!

**Comment by Brett-SustainedAffair** [comment]
> he `theme.liquid` file is not where this is defined, as that file only handles whic

Thanks for your reply Nick! 

I have tried doing the same but this made some UI element render funny. I ended up editing the theme settings on a point-and-click basis in Shopify and managed to make the account page look just like HULL!

**Comment by ansmlc** [comment]
Hi, sorry to drop into a closed thread. I'm trying to use the Hybrid approach, but ever since I changed the DNS settings (A record) for the main domain to point to the new, custom storefront, links like domain.com/account now don't work and can't access the Native Shopify account screen and instead point to HULL's "404 not found" page. 

How do I make an exception so that URLs like "/account" still point to Native Shopify?
