### ISSUE TITLE
I must be missing a step - not seeing my products

### ISSUE THREAD

**Issue by HeyMarcy** [ndimatteo/HULL#23]
Hello and thank you so much for this starter!!
~I used the automatic setup.~
~I've put my shopify environment variables in both vercel and .env.local.  I've followed steps 2 & 3 in the docs to a T.~
~I'm still seeing the starter's original products.~
~Forgive my ignorance. I wish i could give more details. I must be missing a step somewhere.~

**_never mind!  I got it working!_** 
( The environment variable that needed to be regenerated is a bit confusing )

**Comment by HeyMarcy** [comment]
I started over setting it up manually with a new store and new studio project. This time, there aren't any products.
I'm unable to deploy to vercel. I assume this is because there are no products?
Are any 'got-cha's that I may be overlooking?
`
22:22:31.706 | Error occurred prerendering page "/shop". Read more: https://nextjs.org/docs/messages/prerender-error
-- | --
22:22:31.706 | TypeError: Cannot read property 'modules' of null
22:22:31.707 | at Shop (/vercel/path0/.next/server/pages/shop.js:40:37)
22:22:31.708 | at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
22:22:31.708 | at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
22:22:31.708 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
22:22:31.708 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
22:22:31.708 | at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
22:22:31.708 | at Object.renderPage (/vercel/path0/node_modules/next/dist/next-server/server/render.js:54:854)
22:22:31.708 | at Function.getInitialProps (/vercel/path0/.next/server/chunks/859.js:602:19)
22:22:31.708 | at Function.getInitialProps (/vercel/path0/.next/server/pages/_document.js:28:83)
22:22:31.708 | at loadGetInitialProps (/vercel/path0/node_modules/next/dist/next-server/lib/utils.js:5:101)

...
`

**Comment by HeyMarcy** [comment]
never mind! I got it working!
( The environment variable that needed to be regenerated is a bit confusing )

**Comment by justinjerrick** [comment]
@ndimatteo I was having a similar issue until I upgraded to a Vercel Pro account which enables Serverless Functions.

**Comment by ndimatteo** [comment]
@justinjerrick interesting, the Vercel plans indicate that the free Hobby plan includes 12 per deployment: https://vercel.com/docs/platform/limits

Maybe you had more than 12 custom api endpoints that caused some to not be built?
