### ISSUE TITLE
SVG Import support

### ISSUE THREAD

**Issue by hyldmo** [ndimatteo/HULL#27]
While trying to update the logo in my fork I tried replacing `public/HULL-Logo.svg` and quickly noticed it did not work, as this was the actual logo being used:
https://github.com/ndimatteo/HULL/blob/e7f5ec9acec80b6e0810bb408d8f9ae53d6811ba/components/icon.js#L5

I was wondering if adding SVG support is something to consider here (I have a working prototype in a branch, it's just basically adding the `@svgr/webpack` package). It would help with duplications like that and the file becoming cumbersome once you add more SVGs. To keep the color parameter we could just use something like `currentColor`. It might also be unnecessary optimization.

I'll make a PR if it's something that could be worthwhile.

**Comment by ndimatteo** [comment]
Hey there @hyldmo,

Thanks for the suggestion! I believe using inline SVG's is a better solution than importing it as a URL like this.

Here's an old (but good) article for some reasons why: https://css-tricks.com/pretty-good-svg-icon-system/

I know it's a bit more cumbersome to have something as simple as a logo abstracted away into a react component with it's innards stripped out, but I find the consistency of using `<Icon />` creates a solid pattern for displaying your site's icon system wherever needed, and gives you one place to go to edit/adjust :)
