### ISSUE TITLE
Unable to add product swatch colours, validation errors

### ISSUE THREAD

**Issue by j4ysen** [ndimatteo/HULL#28]
Hey! I appreciate everything put into this project, it's amazing!
I'm trying to edit the colours(Options Settings) on products imported from Shopify with multiple variants, and I'm getting an error in sanity studio saying:
`TypeError: modules: Error validating value: undefined is not an object (evaluating 'blocks.filter')`
`TypeError: undefined is not an object (evaluating '_patchEvent.default.from')`

This happens as soon as I press add item on 'Options Settings'..
The same error is thrown when I try and edit an existing product too (eg. Ultra Magic tee). I can't seem to find any sanity documentation about this process. Do you have any ideas as to why this would happen? I haven't made any modifications to the schema supplied. I also get the same error on products with only one variant too if that helps.

Thanks!
Jaysen

**Comment by hyldmo** [comment]
I've seen this happen when only gallery images are added. Have you added cart thumbnail and list images as well?

**Comment by j4ysen** [comment]
Yeah I'm testing on 'Ultra Magic Tee', where I'm just deleting an 'option setting'(blue) and re-adding it
It lets me edit an option setting but not add one

**Comment by j4ysen** [comment]
Update: I ran rm-rf on both studio and the project directory and reset the dependencies to the versions currently on master and it seems to work fine

**Comment by ndimatteo** [comment]
@j4ysen this also might be validation errors coming from the Product's `page modules` array field. It's required to have the "Product Hero" module, so if there are no modules at all the validation can throw some pretty funky errors.

**Comment by j4ysen** [comment]
Yeah I checked that too! Very weird set of errors..
As soon as I reset package.json it worked perfectly.. I think it was an error with sanity studio itself

**Comment by ndimatteo** [comment]
@j4ysen going ot close this, but feel free to open another issue if this pops up again!
