### ISSUE TITLE
Non Sanity pages showing blank screen

### ISSUE THREAD

**Issue by LeoSonnekus** [ndimatteo/HULL#29]
Hey I'm trying to create some other pages and just trying wrap my head around what I believe comes down to site context.

When I add a new page file to the pages directory that isn't being generated by the Sanity page builder and doesn't have any specicifc references to Sanity documents if I try to visit the page in the browser I just get a blank screen with and empty <body> tag.

Why is this? 

If I needed to add pages what's the best way to do this?

**Comment by ndimatteo** [comment]
Hey again @LeoSonnekus!

I'd have to see your new page code to really provide some insight here, but generally speaking you will still need to pass some amount of data if you are wanting things like the global `header`, `footer`, and `cart` to show, even if the actual page content is not coming from Sanity.

Happy to take a look at your page code if you have something specific you're trying to do that isn't working as expected!

**Comment by LeoSonnekus** [comment]
Hey thanks for the response apologies for the late reply (working on a lot at the moment),

Basically if I put a basic page into my /pages directory that looks like this

`import React from 'react'



function login() {


    return (
            <div>
                LOGIN?
            </div>
    )
}

export default login
`
on a fresh Next JS project this would show a blank page with the text LOGIN? and nothing else,

When I put this in my pages directory on a Hull project I see the text for 1-2 seconds then everything disappears.

Do you know why this might be?

Thanks for the help/

**Comment by LeoSonnekus** [comment]
An update on this,

When I add a <Layout> component with only site data (for header and footer and cart details etc.) I don't get this issue, which makes sense but I'd be interested to know why this might be happening without a Layout defined purely so I can understand the tech better.

Thanks for the time.

**Comment by ndimatteo** [comment]
Hey @LeoSonnekus that's very odd. I tested locally and am not seeing the text disappear after 1-2 seconds. I'm wondering if something else is going on in your setup.

**Comment by LeoSonnekus** [comment]
No worries, thanks for the info I'll do more of my own investigating and see if there's something I can find. Cheers!

**Comment by ndimatteo** [comment]
@LeoSonnekus closing this for now, but feel free to open a new issue if you find something!
