### ISSUE TITLE
Question: How do Shopify products get synced to Sanity?

### ISSUE THREAD

**Issue by tmytrn** [ndimatteo/HULL#31]
Hi,

Just wondering how this part works, because everything's running fine except that Sanity isn't pulling my products from Shopify. Not getting any errors regarding my Shopify creds. My guess is it's about the product meta-data?

**Comment by ndimatteo** [comment]
Hey there @tmytrn!

Products get sync'd into Sanity through the following sequence:
1. The `product update` webhook is triggered in Shopify from a product being updated (either from you saving a change, or from an order being placed, reducing the inventory, etc.)
2. If the webhook is setup correctly (reference the setup [step 3](https://github.com/ndimatteo/HULL#3-shopify-webhooks)), it will send the product payload to your API endpoint: `/api/shopify/product-update`
3. The sync function at your API endpoint will do a few checks first to see if there's been a relevant change for the product between the last sync, and if so, update the product in Sanity

A few things to check if you're not seeing your products sync'ing:
- Remember, you must have the webhook notifications setup to a _live_ URL, you cannot use localhost
- All shopify ENV variables must be setup on your live hosting environment
- Your product on Shopify must have your Headless Storefront (private app) enabled for the sales channel

I hope that helps, but let me know if you're still having issues!

**Comment by tmytrn** [comment]
Got em sync'ed! Just didn't have the env variables on live. Thanks Nick!

**Comment by ndimatteo** [comment]
Sweet, glad to hear it @tmytrn! 🤘

**Comment by kobykotiv** [comment]
> * Remember, you must have the webhook notifications setup to a _live_ URL, you cannot use localhost
> * All shopify ENV variables must be setup on your live hosting environment
> * Your product on Shopify must have your Headless Storefront (private app) enabled for the sales channel

Does this mean API links need to by synced between shopify, vericel, AND sanity CMS?

**Comment by ndimatteo** [comment]
@kobykotiv Not sure what you mean by "synced" but to clarify: The API endpoint is setup through Next.js API routing, which is seamlessly executed when hosted on Vercel. This URL is what we tell Shopify to hit so that the product data can be sync'd into Sanity.

In short, they all rely on one another in some capacity.
