### ISSUE TITLE
Incorrect variant shown in preview for product-listing-photos

### ISSUE THREAD

**Issue by kkcy** [ndimatteo/HULL#34]
Hey there, I noticed for all inputs that use dynamic-select, the preview shows 'All Variants' no matter which variant is picked.
Checking the log shows that `forOption` in `prepare` is `undefined`. 

Any idea why?

**Comment by ndimatteo** [comment]
@kkcy there's currently a bug with Sanity Previews that's causing this for array fields with string list fields used in the preview. You can read more about it [here](https://github.com/sanity-io/sanity/issues/2631).

An update should be coming in the next official Sanity Studio release!
