### ISSUE TITLE
Nuxt version?

### ISSUE THREAD

**Issue by patrickbjohnson** [ndimatteo/HULL#35]
Just curious if there will be a Nuxt.js version? :) love the project otherwise.

**Comment by casinolapokerclub** [comment]
Hey there @patrickbjohnson! Thanks for the interest, but no plans to port this to Nuxt.js at the moment.

**Comment by ndimatteo** [comment]
Hey there @patrickbjohnson! Thanks for the interest, but no plans to port this to Nuxt.js at this time.
