### ISSUE TITLE
Cannot delete test products

### ISSUE THREAD

**Issue by justinjerrick** [ndimatteo/HULL#37]
I am receiving the following error when trying to delete the starter demo products:
A document of the unknown type homePage
A document of the unknown type shopPage

When trying to "delete anyway" I receive the following error:
the mutation(s) failed: Document "product-6584939413682" cannot be deleted as there are references to it from "homePage"

All connections have been removed from the products as well.

**Comment by ndimatteo** [comment]
This is due to some legacy documents that are still present in the bundled sanity demo data. You can remove these documents from your terminal with the Sanity CLI. Simply run the following from your studio folder:

```sh
sanity documents delete homePage && sanity documents delete shopPage
```

I'll have this cleaned up in the next release this week 🤘

**Comment by justinjerrick** [comment]
@ndimatteo Thanks. I still seem to be getting an error after running that:

`Error: Failed to delete document:
the mutation(s) failed: Document "homePage" cannot be deleted as there are references to it from "errorPage"
    at Object.<anonymous> (~/Documents/GitHub/camp-final/studio/node_modules/@sanity/core/lib/commands/documents/deleteDocumentsCommand.js:55:15)
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (~/Documents/GitHub/camp-final/studio/node_modules/@sanity/core/lib/commands/documents/deleteDocumentsCommand.js:12:103)
    at _throw (~/Documents/GitHub/camp-final/studio/node_modules/@sanity/core/lib/commands/documents/deleteDocumentsCommand.js:14:291)`

**Comment by ndimatteo** [comment]
@justinjerrick go ahead and delete that document first before running the original command I mentioned:

```sh
sanity documents delete errorPage
```

**Comment by justinjerrick** [comment]
@ndimatteo Thanks that worked 👍

**Comment by GodwinEbikwo** [comment]
Hi, I am still getting the exact problem. When I run the command on the cli, I get
'Document not found: homePage
Document not found: shopPage'

**Comment by ndimatteo** [comment]
@GodwinEbikwo not sure what you mean? The error that the original issue outlines is due to the presence of both of those documents...

If they don't exist, you should not be seeing an [error like this](https://github.com/ndimatteo/HULL/issues/37#issue-977430312).

Please elaborate on what error you are seeing and the steps you are taking to get there. Thanks!
