### ISSUE TITLE
403 error using the Automatic Set Up

### ISSUE THREAD

**Issue by ajmalafif** [ndimatteo/HULL#38]
hey, first and foremost I want to say this template is 🔥🔥🔥

Anyways I wanted to report that I was trying to use the `Automatic Set Up` and received this blocker: https://cln.sh/3RZf32GzMRUTMN17fRto

https://user-images.githubusercontent.com/827167/131335415-d25ce8a7-aed5-4b12-ac51-9d3741b59fb8.mp4

ps: I am actually looking for a good template starter for NextJS + Sanity.io that I don’t have to wire from scratch. HULL seems to do that AND WAY MORE! I love the features include tailwind and framer motion so this is a perfect template for me to start tinkering.

To be honest I don't really need the Shopify (aware of the marketing-starter branch) but since it comes with it so I figured why not play around with it anyways. 

For now, I am not really blocked, trying to do the Manual Set Up way in the meantime and see if I could deploy this on Vercel. Thanks again for sharing this masterpiece as a template 🙇🏻‍♂️

**Comment by ndimatteo** [comment]
Closing for now, we discussed this on the Sanity Community Slack, but just to reiterate: The error seems to be related to Vercel's deployment tool, not this repo.
