### ISSUE TITLE
Products syncing on update when the private app is not selected. 

### ISSUE THREAD

**Issue by highsandlows** [ndimatteo/HULL#59]
When updating products I have 2 private apps that should feed 2 different projects. When the app that is configured with the hull sanity studio is selected in available sales channels and apps for the product the sync works, but the problem is that products with the other app selected also sync to sanity.

**Comment by ndimatteo** [comment]
Hey there @highsandlows! Check out issue #19 where this exact situation is addressed :)

**Comment by highsandlows** [comment]
Thanks @ndimatteo I'm Really enjoying Messing about with HULL you have done a really great job. Trying to keep myself busy while I wait for Shopifys hydrogen to play nice with next.js.
