### ISSUE TITLE
CORS problem, adding product

### ISSUE THREAD

**Issue by Nichtkunst** [ndimatteo/HULL#62]
Hello,
thanks for the great boilerplate. 

ISSUE:
I cannot add products to the cart.

URL: https://hull-shopify-starter-xi-blush.vercel.app/

Reproduce:
* Add product at Homepage (see console in browser then)
* Add product in the productdetails page (see console in browser then)

```
Access to XMLHttpRequest at 'https://h4xropcb.apicdn.sanity.io/v2021-03-25/data/query/production?query=%0A%20%20%20%20%20%20*%5B_type%20%3D%3D%20%22productVariant%22%20%26%26%20variantID%20%3D%3D%2042055549878491%5D%5B0%5D%7B%0A%20%20%20%20%20%20%20%20%22product%22%3A%20*%5B_type%20%3D%3D%20%22product%22%20%26%26%20productID%20%3D%3D%20%5E.productID%5D%5B0%5D%7B%0A%20%20%20%20%20%20%20%20%20%20title%2C%0A%20%20%20%20%20%20%20%20%20%20%22slug%22%3A%20slug.current%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%22id%22%3A%20variantID%2C%0A%20%20%20%20%20%20%20%20title%2C%0A%20%20%20%20%20%20%20%20price%2C%0A%20%20%20%20%20%20%20%20%22photos%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22cart%22%3A%20*%5B_type%20%3D%3D%20%22product%22%20%26%26%20productID%20%3D%3D%20%5E.productID%5D%5B0%5D.cartPhotos%5B%5D%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20forOption%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%22default%22%3A%20cartPhoto%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%22alt%22%3A%20coalesce(alt%2C%20asset-%3EaltText)%2C%0A%20%20asset%2C%0A%20%20crop%2C%0A%20%20customRatio%2C%0A%20%20hotspot%2C%0A%20%20%22id%22%3A%20asset-%3EassetId%2C%0A%20%20%22type%22%3A%20asset-%3EmimeType%2C%0A%20%20%22aspectRatio%22%3A%20asset-%3Emetadata.dimensions.aspectRatio%2C%0A%20%20%22lqip%22%3A%20asset-%3Emetadata.lqip%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20options%5B%5D%7B%0A%20%20%20%20%20%20%20%20%20%20name%2C%0A%20%20%20%20%20%20%20%20%20%20position%2C%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20' from origin 'https://hull-shopify-starter-xi-blush.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

it is related to this query
```
*[_type == "productVariant" && variantID == 42055549878491][0]{
        "product": *[_type == "product" && productID == ^.productID][0]{
          title,
          "slug": slug.current,
        },
        "id": variantID,
        title,
        price,
        "photos": {
          "cart": *[_type == "product" && productID == ^.productID][0].cartPhotos[]{
            forOption,
            "default": cartPhoto{
              
  "alt": coalesce(alt, asset->altText),
  asset,
  crop,
  customRatio,
  hotspot,
  "id": asset->assetId,
  "type": asset->mimeType,
  "aspectRatio": asset->metadata.dimensions.aspectRatio,
  "lqip": asset->metadata.lqip

            },
          }
        },
        options[]{
          name,
          position,
          value
        }
      }
```

**Comment by Nichtkunst** [comment]
I setup the project from sanity directly. 
But I still had to add the CORS origin for http://localhost:3000 and https://[subdomain].vercel.app
This should be mentioned in the steps below when you do the automical setup

Add CORS Origins to your newly created Sanity project (visit: manage.sanity.io and go to Settings > API):
* Add your Studio URLs with credentials: http://localhost:3333 and [subdomain].sanity.studio
* Add your front-end URLs without credentials: http://localhost:3000 and https://[subdomain].vercel.app

**Comment by ndimatteo** [comment]
Hey @Nichtkunst ! Something seems amiss with what you experienced. If you went through the automatic setup through the Sanity Create tool, it should have automatically added these for you. You can see both `http://localhost:3000` and `https://*.vercel.app` are present here in the manifest:

https://github.com/ndimatteo/HULL/blob/main/.sanity-template/manifest.json#L43-L52

Additionally, Sanity automatically adds the `:3333` localhost URL (I know this because previously it was manually included in the manifest above and was causing an error due to duplicate CORS additions).

I'll flag this with the Sanity team to see if they have any insight!

**Comment by 3200pro** [comment]
Just a update on this. I encountered this as well and had to manually add in: https://*.vercel.app to the CORS.
