### ISSUE TITLE
Unexpected behavour if options not configured

### ISSUE THREAD

**Issue by djclarkson** [ndimatteo/HULL#63]
Great project. Just bumped into some unexpected behavior issues. If there is no SEO configured for the home page, the site crashes with the following error. 

```
components/head-seo.js (118:26) @ eval

  116 | 
  117 |   templateTags.map((v) => {
> 118 |     newString = newString.replace(new RegExp(v.tag, 'g'), v.value)
      |                          ^
  119 |   })
  120 | 
  121 |   return newString
```

Once I added SEO that was fixed, but next I got an error for cookie consent bar. Which is disabled by default. By enabling it and adding details this error below went away. 

```
error - components/cookie-bar.js (28:10) @ eval
TypeError: Cannot destructure property 'enabled' of 'data' as it is null.
  26 |
  27 | const CookieBar = React.memo(({ data = {} }) => {
> 28 |   const { enabled, message, link } = data
     |          ^
  29 |
  30 |   if (!enabled) return null
  31 |
```

The next error is for the promo bar. 

```
error - components/header.js (27:4) @ Header
TypeError: Cannot destructure property 'promo' of 'data' as it is null.
  25 |   // expand our header data
  26 |   const {
> 27 |     promo,
     |    ^
  28 |     menuDesktopLeft,
  29 |     menuDesktopRight,
  30 |     menuMobilePrimary,
```

I tried enabling and configuring the promo bar but the error persists. I tried disabling it again and it persists. 

Just wondering if I am missing some configuration. I read the setup instructions again and can't see anything discussing this topic.

**Comment by ndimatteo** [comment]
Hey there @djclarkson thanks for this and apologies for the confusion. These errors are because the front-end assumes at least one document is published for each "setting" in Sanity.

That last one is likely because you don't have a `headerSettings` document published. Once you do, that error should go away.

I'll make a note here to add more checks to ensure the site still builds if documents are missing entirely! Thanks!

**Comment by djclarkson** [comment]
Thanks for the quick reply. One other thing that would be great is when if in development mode that the .env keys are tested and echo to console. Something like:

Testing Shopify Storefront API access....... SUCCESS or FAIL

**Comment by ndimatteo** [comment]
@djclarkson no problem! And there is already a console warning in place if the Shopify ENV variables are not set: https://github.com/ndimatteo/HULL/blob/main/lib/shopify.js#L5-L11

Logging the actual `.env` variables in the console would be a security risk outside of development, so I'm not going to ever include that in HULL out of the box.

I hope that helps!
