### ISSUE TITLE
Manual Set Up: cannot access studio backend locally

### ISSUE THREAD

**Issue by arsnonverba** [ndimatteo/HULL#64]
I'm stuck in the "please sign in" page when trying to access sanity locally. No matter what login option I use, I get thrown back at the "please sign in" page. I verified that my `projectId` matches the one from sanity's dashboard, CORS Origins are placed correctly and the API Token has `read + write` access.

I also deployed sanity to be accesible from the web and get the same error.

Also, the front end throws this error message:

`Home Page" is not set in Sanity, or the page data is missing.`

Any help would be appreciated! Thanks!

**Comment by ndimatteo** [comment]
Hey there @arsnonverba, it sounds like you were able to resolve your own issue!

For issues related to the Sanity service (studio auth), I'd suggest posting in the Sanity Community Slack channel as well. Lots of folks there to help with Sanity-specific issues! 🤘
