### ISSUE TITLE
How to display collections on homepage?

### ISSUE THREAD

**Issue by localghost8000** [ndimatteo/HULL#66]
Hey there,

I'm trying to figure out a way to make adding collections (eg: all vinyl, all t-shirts) as an option to my pages in Sanity (including the homepage). Is there a simple way to achieve this using this template? Thanks

**Comment by ndimatteo** [comment]
Hey there! You could easily achieve this by creating a new page content module that references an existing `collection`, and then using that to render the same `collectionGrid` that is shown on collection pages.

Hopefully that's enough to point you in the right direction, but let me know if you have any further questions!
