### ISSUE TITLE
Trying to deploy theme.liquid

### ISSUE THREAD

**Issue by dev-rroslan** [ndimatteo/HULL#71]
theme deploy --env=production                                                                                       ─╯

invalid environment [production]: (invalid theme_id)

production:
  password: shptka_c2d807afd591c92d93xxxxxxxxxx
  theme_id: "theme.liquid"
  store: open-my-shopify-com.myshopify.com

**Comment by ndimatteo** [comment]
The `theme.liquid` file included in this repo is meant to be copy/pasted manually into your active theme on Shopify. If you're trying to deploy native themes locally that's outside the scope of this project.
