### ISSUE TITLE
Implementing search

### ISSUE THREAD

**Issue by rscheuer** [ndimatteo/HULL#73]
I'm trying to implement a search component based on product titles to the collection page.  (working with a large number of products)  Wondering if you have any tips/best practice ideas to implement this in Hull?  My first thought is to extend the filter component.

Could also be a useful core feature as well?  Thanks for your work on this starter, it's been a huge help.

**Comment by ndimatteo** [comment]
Hey there @rscheuer! This is a great request, and something on the roadmap to add down the line.

If you're looking to implement something simple, that just filters the collection results that functions similar to the existing filter and sort functionality, you could expand on this: https://github.com/ndimatteo/HULL/blob/main/components/modules/collection-grid.js#L94

Passing a `query` string to that as an additional parameter that you could then use to filter out products that don't have a title string that matches the query could likely do the trick!

You could reference something like this to build out this concept within the HULL setup: https://blog.logrocket.com/create-search-bar-react-from-scratch/

If you need something more advanced, I'd highly recommend looking into [Algolia](https://www.algolia.com/doc/)

I hope that helps!

**Comment by rscheuer** [comment]
Thanks Nick!  Super helpful!
