### ISSUE TITLE
Trouble connecting to Shopify APIs nor Klaviyo

### ISSUE THREAD

**Issue by where-is-brett** [ndimatteo/HULL#81]
Hi Nick, you've create an awesome headless starter! Thanks for making it available to everyone. 

I am really struggling to connect to my Shopify development store. I have followed the instructions to add shopify & klaviyo environment variables to both .env in the project folder and Vercel's environment variable settings:

`SHOPIFY_STORE_ID=xxxxxxxx`
`SHOPIFY_API_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` (Storefront API access token)
`SHOPIFY_API_PASSWORD=xxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxx` (API secret key)
`SHOPIFY_WEBHOOK_INTEGRITY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` (settings -> notification -> beneath webhooks)
`KLAVIYO_API_KEY= xx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` (private API key)

The Klaviyo public API key in the footer was updated through sanity studio. I then created a product in Shopify and updated another, but still only the HULL sample data was displayed in sanity studio. I also tried to subscribe to the mailing list but this did not work either ("Whoops! That didn't work.").

I can see from the deployment log that only two environment variables are included:

`> hull@2.5.0 build`
`> echo 'Building Sanity to public/studio…' && cd studio && npx sanity build ../public/studio -y && cd .. && next build`
`>Building Sanity to public/studio… Including the following environment variables as part of the JavaScript bundle:`
`- SANITY_STUDIO_API_PROJECT_ID`
`- SANITY_STUDIO_API_DATASET`

My project was created via the automatic setup you had provided, the variables were subsequently added before deployment. Am I missing something here? Any help would be appreciated!

Cheers,
Brett

**Comment by where-is-brett** [comment]
Update on Klaviyo API:

After I had discovered that Vercel has an error log for serverless functions (still very new to the game), I was able to pin point the problem in my case. I was able to resolve the issue by using Klaviyo list ID instead of public API key in sanity studio settings.

I still haven't worked out the Shopify connection though.

**Comment by where-is-brett** [comment]
Update on Shopify APIs:

Now that I am able to see the error log, I was able to look further into the problem. It turned out that I had mistaken `SHOPIFY_API_PASSWORD` for API private key. It is in fact the admin API key. The picture below shows the correct setup.
<img width="1445" alt="Screen Shot 2022-02-25 at 12 49 01 pm" src="https://user-images.githubusercontent.com/79561827/155638732-3977c0a3-f294-498a-b3bd-2d4ec53b1d80.png">

**Comment by where-is-brett** [comment]
The question remains, what should I use for this field?

<img width="1662" alt="Screen Shot 2022-02-25 at 12 55 28 pm" src="https://user-images.githubusercontent.com/79561827/155639630-49c18cb5-9919-4d0e-8e95-615507c3f8ea.png">

The newsletter worked when both this field and the footer were list ID. Is this the intended use for this field?

**Comment by ndimatteo** [comment]
Hey there @where-is-brett !

Glad you were able to figure out the Shopify `.env` variables, I know it can be a bit tricky (especially with their newly redesigned app UI).

As for Klaviyo, you should be entering in what it's specifying for both places.

You also need to add the `KLAVIYO_API_KEY` (private API key) to your `.env` variables as [outlined in the readme file](https://github.com/ndimatteo/HULL#4-nextjs).

All of these can be found from your klaviyo account:
- **List ID:** Lists & Segments -> "three dots" -> List Settings -> "List ID & Name"
- **Public API Key:** Account -> Settings -> API Keys -> "Public API Key / Site ID"
- **KLAVIYO_API_KEY:** Account -> Settings -> API Keys -> Create a "Private API Key"
