### ISSUE TITLE
Product syncing off of shopify not working right now

### ISSUE THREAD

**Issue by ClarkYin** [ndimatteo/HULL#85]
Hello!

I saw previous issues about syncing issues and i actually did not have any issues until i made some changes to my vercal...and now i do. I'm not sure why and i've triple checked everything but i must be missing something! I now have these errors here please help

![image](https://user-images.githubusercontent.com/6474185/160762788-5d98eb10-5640-4bc4-8f44-cb9341a923a6.png)

**Comment by ClarkYin** [comment]
@ndimatteo Very strange! it looks like it's work now after i went to bed last night and came back...I can only assume that it takes some time for the Sanity Token to be activated (Hmm!?) Thanks!

**Comment by ndimatteo** [comment]
@ClarkYin there shouldn't be a delay in Sanity Token's working or not. One thing to note though, is that you do need to redeploy on Vercel after changing environment variables. They are implemented during deployment so making a change afterwards will not reflect on your live site until the next deploy. That might be why you weren't seeing any difference after changing these.

Beyond that, it's hard to see any other explanation for the issue you encountered. Either way, the errors in your screenshot directly point to Sanity. So, if you run into it again and are certain that the in-use `env` variable for the Sanity Token has write access, I'd suggest reaching out in the Sanity Community Slack for some assistance from their team.

I hope that helps, going to close this as it seems to be resolved 🤘

**Comment by ClarkYin** [comment]
@ndimatteo Yeah i think i did a few deployments prior but maybe due to my improper setup prior it still wasn't working, thanks! all makes sense.
