### ISSUE TITLE
Your focus-trap must have at least one container with at least one tabbable node in it at all times

### ISSUE THREAD

**Issue by geniti** [ndimatteo/HULL#88]
This happens a lot not sure how to solve

**Comment by ndimatteo** [comment]
Hey there @geniti !

This can happen if there isn't a link/button within the `<FocusTrap />` component and there is animations happening that could cause it to not be focusable when the focus trap component mounts.

There's a few solutions here:

1. Default the FocusTrap's `active` prop to false until the animation is complete
2. Set a `fallbackFocus` ref via the `focusTrapOptions` prop

I hope that helps, but let me know if you run into any specific issues with the core HULL components using FocusTrap!

**Comment by ndimatteo** [comment]
Closing this, but holler if you have any more issues with this @geniti

**Comment by ullas1000** [comment]
this is due to none availability of tabbable controls.
https://devphobia.com/posts/Your-focus-trap-must-have-at-least-one-container
