### ISSUE TITLE
<script> in theme.liquid triggering NextJS error

### ISSUE THREAD

**Issue by 3200pro** [ndimatteo/HULL#98]
Hi Nick,

I'm getting the following error firing for every page loaded regarding the <script> tag in the theme.liquid file:

`Do not add <script> tags using next/head (see inline <script>). Use next/script instead.`

Any thoughts on how to disable/ignore this error?

**Comment by ndimatteo** [comment]
Hey there @3200pro! The `theme.liquid` file is exclusively used for your Shopify native theme (it's meant to be copy/pasted there).

Did you happen to move that file from the repo root? By default, that file shouldn't be affecting anything to do with the Next.js build as it's not referenced or used in the Next.js application structure.

**Comment by 3200pro** [comment]
Thanks Nick!

I didn't realize it should be deleted from the root folder after it's copied/pasted to Shopify.
