### ISSUE TITLE
Data Error: "Home Page" is not set in Sanity, or the page data is missing.

### ISSUE THREAD

**Issue by khushmanvar** [ndimatteo/HULL#99]
![Screenshot from 2022-06-13 11-37-38](https://user-images.githubusercontent.com/54769548/173290318-4000b525-a7ed-4ba4-afef-5b992fa163c3.png)
Getting the above error, even after doing all instructions correctly. Can anyone please help me solving this?

**Comment by ndimatteo** [comment]
Hey there @khushmanvar!

This error means it couldn't fetch the data needed from Sanity to render the home page.

Are there any other consol errors associated with this that you can share?

Some other things to check:
1. Make sure you've published all "settings" documents
2. Make sure you've created a page with content on it
3. Make sure you've set the home page reference to the page you created here: **Settings > General > Displays (tab)**

Let me know if that makes sense! You're almost there 🤘

**Comment by ndimatteo** [comment]
Closing this for now @khushmanvar, but follow up here if you run into any other issues related to this 🤘

**Comment by enterpriseSoftware** [comment]
I got the same error after following the directions.  I cloned the repository with git clonee and followed the instructions in the ReadMe.md file in the root.  Localhost:3333 and localhost:3000 are running, I don't see any errors.
$ yarn dev
yarn run v1.22.21
warning ..\package.json: License should be a valid SPDX license expression
$ cross-env NODE_ENV=development next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\SourceControl\HULL\.env.local
event - compiled client and server successfully in 8.7s (1836 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2s (1937 modules)


$ yarn dev
yarn run v1.22.21
warning ..\..\package.json: License should be a valid SPDX license expression
$ sanity start


   ╭────────────────────────────────────────────╮
   │                                            │
   │     Update available 2.36.2 → 3.30.0       │
   │   Run yarn upgrade @sanity/cli to update   │
   │                                            │
   ╰────────────────────────────────────────────╯


[WARN] The following package versions have not yet been marked as supported:

  react (installed: 18.2.0, want: ^16.9 || ^17)
  react-dom (installed: 18.2.0, want: ^16.9 || ^17)

You _may_ encounter bugs while using these versions.

  To downgrade, run either:

  yarn add "react@17.0.0" "react-dom@17.0.0"

  or

  npm install "react@17.0.0" "react-dom@17.0.0"


✔ Checking configuration files...
⠙ Compiling...webpack built cb72540ebe37085a9011 in 16584ms
✔ Compiling...
Content Studio successfully compiled! Go to http://localhost:3333
![localhost3333](https://github.com/ndimatteo/HULL/assets/6784635/0f1e2460-9189-4be9-8639-378e5a3b6c1f)

**Comment by ndimatteo** [comment]
@enterpriseSoftware please see the comment above (quoted below as well). You need to begin filling out your content if you didn't import via the Sanity CLI. This is not an error, this is expected behavior when there is not page data to fetch for the home page.

> This error means it couldn't fetch the data needed from Sanity to render the home page.
> 
> Are there any other consol errors associated with this that you can share?
> 
> Some other things to check:
> 
> 1. Make sure you've published all "settings" documents
> 2. Make sure you've created a page with content on it
> 3. Make sure you've set the home page reference to the page you created here: **Settings > General > Displays (tab)**
> 
> Let me know if that makes sense! You're almost there 🤘
